# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ravi RT Merugu
email: rrmerugu@gmail.com
userslogan: Its all about Coke Cofee and Code
description: > # I'm Ravi Raja Merugu and I love Coffee, Coke and Code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rrmerugu.github.io" # the base hostname & protocol for your site


disclaimer: The content on this site represents my own personal opinions and thoughts at the time of posting.
 
twitter_username: rrmerugu
github_username:  rrmerugu


# permalink: /:title.html #/:year/:month/title
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
